# Generated by Django 4.2.4 on 2023-08-06 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=250)),
                ('Address1', models.CharField(max_length=500)),
                ('Address2', models.CharField(max_length=500)),
                ('Address3', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'A. Company',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=250)),
                ('Coursecode', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'J.  Course',
            },
        ),
        migrations.CreateModel(
            name='Enquiry_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquirysourcename', models.CharField(max_length=250)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'E. Enquiry source',
            },
        ),
        migrations.CreateModel(
            name='Follow_up_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followupstatusname', models.CharField(max_length=150)),
                ('Followupstatus', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=35)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'F. Follow up status',
            },
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'I.  Master Data',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualificationname', models.CharField(max_length=250)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'G. Qualification',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'B. State',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.CharField(max_length=1000)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'H.  Syllabus',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=250)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
            ],
            options={
                'verbose_name_plural': 'c. District',
            },
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=250)),
                ('Branch_code', models.CharField(max_length=250)),
                ('Address', models.CharField(blank=True, max_length=250)),
                ('Street', models.CharField(blank=True, max_length=250)),
                ('Pincode', models.CharField(blank=True, max_length=12)),
                ('Mobile', models.CharField(max_length=25)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
                ('district', smart_selects.db_fields.ChainedForeignKey(chained_field='State', chained_model_field='State', on_delete=django.db.models.deletion.CASCADE, to='settings.district', verbose_name='District')),
            ],
            options={
                'verbose_name_plural': 'd. Branch',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Closed', models.BooleanField()),
                ('Active', models.BooleanField(default=True)),
                ('Trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.courses')),
            ],
            options={
                'verbose_name_plural': 'K.  Batch',
            },
        ),
    ]
