# Generated by Django 4.2.4 on 2023-08-06 04:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=250)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Dob', models.DateField(max_length=8)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Photo', models.ImageField(upload_to='')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.courses')),
                ('District', smart_selects.db_fields.ChainedForeignKey(chained_field='State', chained_model_field='State', on_delete=django.db.models.deletion.CASCADE, to='settings.district', verbose_name='District')),
                ('Enquiry_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.enquiry_source')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
            ],
        ),
    ]
