# Generated by Django 4.2.4 on 2023-08-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_feedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student',
            new_name='student',
        ),
    ]
