# Generated by Django 4.2.4 on 2023-08-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_student_student_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedetails',
            old_name='Student',
            new_name='Studentname',
        ),
    ]
