# Generated by Django 4.2.4 on 2023-08-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('students', '0004_rename_student_feedetails_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='coursename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.courses'),
        ),
    ]
