# Generated by Django 4.2.4 on 2023-08-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_feedetails_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedetails',
            name='coursename',
        ),
    ]
